### ISSUE TITLE
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql

### ISSUE THREAD

**Issue by rchannel** [errbotio/err-storage-sql#5] opened 2016-09-21 19:34 UTC
Attempting to use I am getting the following errors in the subject line and in the following Gist.
https://gist.github.com/rchannel/2a2e0223f42a6071716ffaf47a88d994

**Comment by rchannel** [comment] 2016-09-21 19:44
I see this has been posted previously but do not see a solution in the previous posting either.

**Comment by sijis** [comment] 2016-10-05 17:34
This is related to #1.
We worked through in gitter and the suggestions noted in #1 seemed to have worked.

**Comment by zoni** [comment] 2016-10-05 17:59
Closing this as it appears a duplicate of #1.

We really need to fix this. Unfortunately I don't have time myself to curate a proper fix. (#3 has a lot of good stuff but is a pretty big PR).

**Closed as completed by zoni** 2016-10-05 17:59 UTC
